---
encoding: utf8
default_branch: main
collapse_pre_releases: true
pre_release_tag_re: (?P<pre_release>(?:[ab]|rc|pre)+\d*)$
unreleased_version_title: Unreleased Notes Preview
sections:
  - [features, New Features]
  - [features_c, C API Features]
  - [features_circuits, Circuits Features]
  - [features_primitives, Primitives Features]
  - [features_providers, Providers Features]
  - [features_qasm, OpenQASM Features]
  - [features_qpy, QPY Features]
  - [features_quantum_info, Quantum Information Features]
  - [features_synthesis, Synthesis Features]
  - [features_transpiler, Transpiler Features]
  - [features_visualization, Visualization Features]
  - [features_misc, Miscellaneous Features]
  - [upgrade, Upgrade Notes]
  - [upgrade_c, C API Upgrade Notes]
  - [upgrade_circuits, Circuits Upgrade Notes]
  - [upgrade_primitives, Primitives Upgrade Notes]
  - [upgrade_providers, Providers Upgrade Notes]
  - [upgrade_qasm, OpenQASM Upgrade Notes]
  - [upgrade_qpy, QPY Upgrade Notes]
  - [upgrade_quantum_info, Quantum Information Upgrade Notes]
  - [upgrade_synthesis, Synthesis Upgrade Notes]
  - [upgrade_transpiler, Transpiler Upgrade Notes]
  - [upgrade_visualization, Visualization Upgrade Notes]
  - [upgrade_misc, Miscellaneous Upgrade Notes]
  - [deprecations, Deprecation Notes]
  - [deprecations_c, C API Deprecations]
  - [deprecations_circuits, Circuits Deprecations]
  - [deprecations_primitives, Primitives Deprecations]
  - [deprecations_providers, Providers Deprecations]
  - [deprecations_qasm, OpenQASM Deprecations]
  - [deprecations_qpy, QPY Deprecations]
  - [deprecations_quantum_info, Quantum Information Deprecations]
  - [deprecations_synthesis, Synthesis Deprecations]
  - [deprecations_transpiler, Transpiler Deprecations]
  - [deprecations_visualization, Visualization Deprecations]
  - [deprecations_misc, Miscellaneous Deprecations]
  - [build, Build System Changes]
  - [issues, Known Issues]
  - [critical, Critical Issues]
  - [security, Security Issues]
  - [fixes, Bug Fixes]
  - [other, Other Notes]
template: |
  ---
  # Delete all sections that you do not need.  You can have more than one section in a file, and
  # more than one bullet point per section.  This is a regular YAML file, and all text should use
  # Sphinx's flavor of rST (restructured text).  Each bullet point is a separate "release note".
  #
  # Each public bug fix, feature, deprecation, and behavior change needs a release note.
  # Documentation- or internal-only changes do not need release notes.
  #
  # Each bullet point appears without any context, so make sure each can be read in isolation.  The
  # reader will not see your code change, the issue, or any other bullet points in this file.  You
  # might need to repeat yourself between bullets.
  #
  # Use Sphinx cross-references like :meth:`.YourClass.your_method` whenever mentioning a
  # function/class/method by name.
  #
  # Use `- |` for multiline YAML strings (like in the "fixes" example in this template) to preserve
  # newlines, which you need for Sphinx syntax.
  #
  # There are some rare additional sections listed in `releasenotes/config.yaml` not included here.

  fixes:
    - |
      Give each bug fix a separate bullet point in here, or delete this section.
      Each bug-fix note should be about one sentence long.  You can link to
      issues such as by doing:

      See `#15019 <https://github.com/Qiskit/qiskit/issues/15019>`__.

  # Choose only the "features" sections you need and delete the rest.  Try to be concise.  You may
  # use a code example for complicated features.
  features_c:
    - New features in the C API.
  features_circuits:
    - New features in :mod:`qiskit.circuit`.
  features_primitives:
    - New features in :mod:`qiskit.primitives`.
  features_providers:
    - New features in :mod:`qiskit.providers`.
  features_qasm:
    - New features in :mod:`qiskit.qasm2` or :mod:`qiskit.qasm3`.
  features_qpy:
    - New features in :mod:`qiskit.qpy` or changes to the QPY spec.
  features_quantum_info:
    - New features in :mod:`qiskit.quantum_info`.
  features_synthesis:
    - New features in :mod:`qiskit.synthesis`.
  features_transpiler:
    - New features in :mod:`qiskit.transpiler`, including all transpiler passes and also the
      :class:`.DAGCircuit` intermediate representation (IR).
  features_visualization:
    - New features in :mod:`qiskit.visualization`.
  features_misc:
    - New features that don't fit into any other category.

  # Release notes for changes that might require users to modify their code.  These should not be
  # common, because breaking user code is against the deprecation policy.
  upgrade_c:
    - Changes needing user action in the C API.
  upgrade_circuits:
    - Changes needing user action in :mod:`qiskit.circuit`.
  upgrade_primitives:
    - Changes needing user action in :mod:`qiskit.primitives`.
  upgrade_providers:
    - Changes needing user action in :mod:`qiskit.providers`.
  upgrade_qasm:
    - Changes needing user action in :mod:`qiskit.qasm2` or :mod:`qiskit.qasm3`.
  upgrade_qpy:
    - Changes needing user action in :mod:`qiskit.qpy` or changes to the QPY spec.
  upgrade_quantum_info:
    - Changes needing user action in :mod:`qiskit.quantum_info`.
  upgrade_synthesis:
    - Changes needing user action in :mod:`qiskit.synthesis`.
  upgrade_transpiler:
    - Changes needing user action in :mod:`qiskit.transpiler`, including all transpiler passes
      and also the :class:`.DAGCircuit` IR.
  upgrade_visualization:
    - Changes needing user action in :mod:`qiskit.visualization`.
  upgrade_misc:
    - Changes needing user action that don't fit into any other category.

  # New deprecations in this release.  Each deprecation should explain why the deprecation is
  # necessary, and what users should do instead.  Include examples.
  deprecations_c:
    - New deprecations in the C API.
  deprecations_circuits:
    - New deprecations in :mod:`qiskit.circuit`.
  deprecations_primitives:
    - New deprecations in :mod:`qiskit.primitives`.
  deprecations_providers:
    - New deprecations in :mod:`qiskit.providers`.
  deprecations_qasm:
    - New deprecations in :mod:`qiskit.qasm2` or :mod:`qiskit.qasm3`.
  deprecations_qpy:
    - New deprecations in :mod:`qiskit.qpy` or changes to the QPY spec.
  deprecations_quantum_info:
    - New deprecations in :mod:`qiskit.quantum_info`.
  deprecations_synthesis:
    - New deprecations in :mod:`qiskit.synthesis`.
  deprecations_transpiler:
    - New deprecations in :mod:`qiskit.transpiler`, including all transpiler passes and also the
      :class:`.DAGCircuit` IR.
  deprecations_visualization:
    - New deprecations in :mod:`qiskit.visualization`.
  deprecations_misc:
    - New deprecations that don't fit into any other category.

  # Build release notes are for things like Rust-version updates, Python-packaging updates, etc.
  # These generally shouldn't concern users, just people building from source.
  build:
    - Changes to the build system that packagers might need to be aware of.
