---
upgrade_providers:
  - |
    The ``configuration`` method of :class:`.BasicSimulator` has been removed following its deprecation
    in Qiskit 1.3. This method returned a ``BackendConfiguration`` instance, and this class was
    part of the deprecated ``BackendV1`` workflow. The individual configuration elements 
    can be retrieved directly from the backend or from the contained :class:`.Target` instance ``(backend.target)``.

  - |
    The ``run_experiment`` method of :class:`.BasicSimulator` has also been removed. This method took an instance
    of the ``QasmQobjExperiment`` class as an input argument, and the class has been deprecated since Qiskit 1.2.
