---
# Merge queue.  A PR that reaches here has already passed the more rigorous PR
# suite, so is very likely to pass.  The main reasons for failures here are
# flaky VMs timing out (which we can't do much about), or a merge conflict
# with another PR that is also in the merge queue.
#
# There's no reason to have multiple stages in this case, because we're
# expecting it to pass.  Having more than one stage frustrates parallel
# throughput in low-contention cases, and guarantees a longer critical path.
name: Merge queue
on:
  merge_group:
    branches: [main, "stable/*"]
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docs_lint:
    if: github.repository_owner == 'Qiskit'
    name: Docs and Lint
    uses: ./.github/workflows/lint_docs.yml
  test-linux-3-10:
    name: Python Unit Tests
    if: github.repository_owner == 'Qiskit'
    uses: ./.github/workflows/test-linux.yml
    strategy:
      matrix:
        runner: ["ubuntu-latest", "ubuntu-24.04-arm"]
    with:
      python-version: "3.10"
      install-optionals: true
      runner: ${{ matrix.runner }}
      qiskit-pycache: false
  test-linux-3-13:
    name: Python Unit Tests
    if: github.repository_owner == 'Qiskit'
    uses: ./.github/workflows/test-linux.yml
    strategy:
      matrix:
        runner: ["ubuntu-latest", "ubuntu-24.04-arm"]
    with:
      python-version: "3.13"
      install-optionals: false
      runner: ${{ matrix.runner }}
  test-rust:
    name: Rust Unit Tests
    if: github.repository_owner == 'Qiskit'
    uses: ./.github/workflows/rust-tests.yml
    with:
      python-version: "3.10"
      runner: "ubuntu-latest"
  test-images:
    name: Image Comparison Tests
    if: github.repository_owner == 'Qiskit'
    uses: ./.github/workflows/image-tests.yml
    with:
      python-version: "3.10"
      runner: "ubuntu-latest"
  test-mac:
    name: Python Unit Tests
    if: github.repository_owner == 'Qiskit'
    uses: ./.github/workflows/test-mac.yml
    strategy:
      matrix:
        python-version: ["3.13"]
        runner: ["macos-14"]
    with:
      python-version: ${{ matrix.python-version }}
      install-optionals: false
      runner: ${{ matrix.runner }}
  test-windows:
    name: Python Unit Tests
    if: github.repository_owner == 'Qiskit'
    uses: ./.github/workflows/test-windows.yml
    strategy:
      matrix:
        python-version: ["3.13"]
        runner: ["windows-latest"]
    with:
      python-version: ${{ matrix.python-version }}
      install-optionals: false
      runner: ${{ matrix.runner }}
  c-tests:
    if: github.repository_owner == 'Qiskit'
    name: C API Unit Tests
    uses: ./.github/workflows/ctests.yml
