name: QPY

on:
  push:
    branches:
      - 'main'
      - 'stable/*'
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  backward_compat:
    if: github.repository_owner == 'Qiskit'
    name: Backwards compatibility
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        # This version needs to be large enough to support Qiskit on `main`, and old enough to
        # support the oldest version of Symengine we test against.
        with:
          python-version: '3.10'

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v4
        with:
          path: test/qpy_compat/qpy_cache
          # The hashing is this key can be too eager to invalidate the cache,
          # but since we risk the QPY tests failing to update if they're not in
          # sync, it's better safe than sorry.
          key: qpy-${{ hashFiles('test/qpy_compat/**') }}

      - name: Run QPY backwards compatibility tests
        working-directory: test/qpy_compat
        run: ./run_tests.sh
        env:
          QISKIT_IGNORE_USER_SETTINGS: TRUE
