name: Slow nightly tests
on:
  schedule:
    - cron:  '42 3 * * *'
  workflow_dispatch:
jobs:
  slow-tests:
    if: github.repository_owner == 'Qiskit'
    name: Full-test-run-with-slow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        name: Install Python
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U \
            -c constraints.txt \
            --group test \
            -r requirements-optional.txt \
            -e .
        env:
          QISKIT_BUILD_PROFILE: release
      - name: Run all tests including slow
        run: stestr run --slowest
        env:
          RUST_BACKTRACE: 1
          QISKIT_TESTS: "run_slow"
          QISKIT_IGNORE_USER_SETTINGS: TRUE
      - name: Create comment on failed test run
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: 7864
          body: |
            Nightly slow test run failed at commit ${{ github.sha }}.

            _Logs_: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
