name: Slow nightly tests
on:
  schedule:
    - cron:  '42 3 * * *'
  workflow_dispatch:
jobs:
  slow-tests:
    name: Full-test-run-with-slow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -U -r requirements.txt -c constraints.txt
          pip install -U -r requirements-dev.txt -c constraints.txt
          pip install -c constraints.txt -e .
          pip install "qiskit-aer" "z3-solver" "cplex" -c constraints.txt
        env:
          SETUPTOOLS_ENABLE_FEATURES: "legacy-editable"
      - name: Run all tests including slow
        run: stestr run
        env:
          RUST_BACKTRACE: 1
          QISKIT_TESTS: "run_slow"
      - name: Create comment on failed test run
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 7864
          body: |
            Nightly slow test run failed at commit ${{ github.sha }}.

            _Logs_: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
